// Auto-generated by backend/packages/midnight/contract-pvp-deploy.ts — do not edit manually.
// Run `deno task -f @pvp-arena-backend/midnight-contracts contract-pvp:deploy` to update.
export const UNDEPLOYED_CONTRACT_ADDRESS = 'e8ef06ae9493c5f3d125f10351bec27887f82dbc8179eb631ffb3f3ccf909e76';
export const PREPROD_CONTRACT_ADDRESS = '9c6df2eea3e452c0c981d1ac073400e7d0e313d4d1f01b44edea565db71987a2';
export const MAINNET_CONTRACT_ADDRESS = '';
