// Auto-generated by backend/packages/midnight/contract-pvp-deploy.ts — do not edit manually.
// Run `deno task -f @pvp-arena-backend/midnight-contracts contract-pvp:deploy` to update.
export const UNDEPLOYED_CONTRACT_ADDRESS = '502c5f33e681f52a1ec26d4a1a8a91fa4a7358e79f0cb19e8d1c02988e933843';
