// Auto-generated by backend/packages/midnight/contract-pvp-deploy.ts — do not edit manually.
// Run `deno task -f @pvp-arena-backend/midnight-contracts contract-pvp:deploy` to update.
export const UNDEPLOYED_CONTRACT_ADDRESS = '4b35f9d5ef36c436b154a0f5dff8deba18e5ba76ea82cecd38059755084b1403';
export const PREPROD_CONTRACT_ADDRESS = '9c6df2eea3e452c0c981d1ac073400e7d0e313d4d1f01b44edea565db71987a2';
export const MAINNET_CONTRACT_ADDRESS = '6d5d061752943e89213f576cdec7a732d907dad8e51371eb012bf525ecabd523';
